name: sync-download
author: gendloop
description: 'sync-download'
inputs:
# Required
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: checkout-curr-repo
      uses: actions/checkout@v3
      with: 
        path: ./Temp
        token: ${{ inputs.token }}

    - name: checkout-downloader
      uses: actions/checkout@v3
      env:
        downloader_path: './TempTools'
      with: 
        repository: 'gendloop/Tools'
        path: ${{ env.downloader_path }}
        ref: 'main'
        token: ${{ inputs.token }}
      
    # - name: find-bash.exe
    #   shell: cmd
    #   run: |
    #     where bash

    # - name: add-path-to-environment-variable
    #   shell: bash
    #   run: |
    #     if [[ ${RUNNER_OS} == "windows-latest" ]] 
    #     then
    #       echo "PATH=\${PATH}:/c/Program Files/Git/bin" >> $GITHUB_ENV
    #     fi
    - name: install git bash
      shell: pwsh
      run: |
        # sudo apt-get update
        sudo apt-get install -y git bash

        # git config --global core.autocrlf false
        # git config --global core.eol lf
        # git config --global credential.helper 'cache --timeout=3600'

    - name: sync-downloaded-files
      shell: pwsh
      working-directory: ${{ github.workspace }}
      env:
        downloader_path: './TempTools'
      run: |
        ${{ env.downloader_path }}/Common/DownloadFileFromRepo/downloadFilesFromRepo.ps1 ./Temp/scripts

    - name: git-push
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ github.token }}
        commit: "chore: sync-downloaded-files"
        workspace: ${{ github.workspace }}/Temp

